lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - lib/nfcore_external_java_deps.jar
    - lib/NfcoreSchema.groovy
    - lib/NfcoreTemplate.groovy
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
  files_unchanged:
    - LICENCE
    - lib/NfcoreTemplate.groovy
    - CODE_OF_CONDUCT.md
    - assets/sendmail_template.txt
    - assets/email_template.html
    - assets/email_template.txt
    - assets/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/CONTRIBUTING.md
    - .github/workflows/linting_comment.yml
    - .gitignore
    - .prettierignore
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.max_cpus
    - params.max_memory
    - params.max_time
    - params.show_hidden_params
    - params.schema_ignore_params
    - params.validationSchemaIgnoreParams
  template_strings: False
  merge_markers: False
repository_type: pipeline
template:
  author: priyanka-surana
  description: Quality assessment of genome assemblies
  name: blobtoolkit
  prefix: sanger-tol
  skip:
    - igenomes
