lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - LICENCE
    - lib/NfcoreTemplate.groovy
    - CODE_OF_CONDUCT.md
    - assets/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_light.png
    - docs/images/nf-core-blobtoolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  template_strings: False
  merge_markers: False
repository_type: pipeline
template:
  author: priyanka-surana
  description: Quality assessment of genome assemblies
  name: blobtoolkit
  prefix: sanger-tol
  skip:
    - igenomes
