repository_type: pipeline
lint:
  actions_ci: False
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
