contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #blobtoolkit channel"
    url: https://nfcore.slack.com/channels/blobtoolkit
    about: Discussion about the nf-core/blobtoolkit pipeline
